channel_sources:                              # [win]
  - conda-forge/label/meson_dev,conda-forge   # [win]
#fortran_compiler:              # [win]
#  - flang                      # [win]
#fortran_compiler_version:      # [win]
#  - 17                         # [win]
# OpenBLAS on windows uses flang5 for some reason, so need mkl instead, but mkl brings intel-openmp which clashes with llvm-openmp
# See https://github.com/conda-forge/scipy-feedstock/issues/257
# See https://github.com/conda-forge/impactx-feedstock/blob/main/recipe/meta.yaml
# https://conda-forge.org/docs/maintainer/knowledge_base/#blas
#blas_impl:
#    - openblas    # [ not win ]
#    - blis        # [ win ]
#llvm_openmp:      # [osx or win]
#    - 17          # [osx or win]
