channel_sources:                              # [win]
  - conda-forge/label/meson_dev,conda-forge   # [win]
fortran_compiler:              # [win]
  - flang                      # [win]
fortran_compiler_version:      # [win]
  - 17                         # [win]
blas_impl:
    - openblas    # [ not win ]
    - blis        # [ win ]
