m2w64_c_compiler:                # [win]
  - m2w64-gcc                    # [win]
m2w64_fortran_compiler:          # [win]
  - m2w64-gcc-fortran            # [win]
fortran_compiler:                # [win]
  - m2w64-gcc-fortran            # [win]
