{% set version = "1.2.6" %}

package:
  name: pyhams
  version: {{ version }}

source:
  url: https://github.com/WISDEM/pyHAMS/archive/v{{ version }}.tar.gz
  sha256: 28d1b347a4f2ae287a87fdcec5ea69ff05d53e6cb1cfe32efdc4ca74dd21b6c7
  # Download the tar-ball and do: openssl sha256 file.tar.gz to update
  patches:
    - meson_files.patch

build:
  number: 0
  skip: true  # [py<39]
  #script:
  #  - echo "python = '${PREFIX}/bin/python'" >> ${BUILD_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
  #  - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}               # [not win]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - python                                  # [build_platform != target_platform]
    - meson-python
    - meson
    - ninja
    - pkg-config
    - numpy
    # pythran code needs clang-cl on windows
    - clang                                  # [win]
    # use flang as fortran compiler on windows (uses clang driver)
    - flang                                  # [win]
    # use llvm linker for both of the above
    - lld                                    # [win]    
    # Cmake is needed to help find libraries on windows
    - cmake         # [win]
    - llvm-openmp
    - openblas      # [win]
  host:
    - compiler-rt                            # [win]
    - cython
    - python
    - pip
    - python-build
    - numpy
    - openblas
    - meson
    - meson-python
    - ninja
    - llvm-openmp
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - ninja
    - libopenblas
    - llvm-openmp

test:
  imports:
    - pyhams
    - pyhams.pyhams
  requires:
    - pytest
  source_files:
    - test  # [ not win ]
  commands:
    - "cd test; pytest .; cd ..;"  # [ not win ]


about:
  home: https://github.com/WISDEM/pyHAMS
  license: Apache-2.0
  license_file: LICENSE
  summary: Python module wrapping around HAMS
  dev_url: https://github.com/WISDEM/pyHAMS

extra:
  recipe-maintainers:
    - mattEhall
    - dzalkind
    - gbarter
    - lucas-carmo
