{% set version = "1.2.6" %}

package:
    name: pyhams
    version: {{ version }}

source:
    url: https://github.com/WISDEM/pyHAMS/archive/v{{ version }}.tar.gz
    sha256: 28d1b347a4f2ae287a87fdcec5ea69ff05d53e6cb1cfe32efdc4ca74dd21b6c7
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
    patches:
        - meson_files.patch

build:
    number: 1
    skip: true  # [py<39]
    #script:
    #  - echo "python = '${PREFIX}/bin/python'" >> ${BUILD_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    #  - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - meson                                  # [build_platform != target_platform]
        - meson-python                           # [build_platform != target_platform]
        - ninja                                  # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pkg-config                             # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}              # [unix]
        - clang                                  # [win]
        - flang                                  # [win]
        - lld                                    # [win]
    host:
        - compiler-rt                            # [win]
        - meson
        - meson-python
        - llvm-openmp                            # [osx or win]
        - libgomp                                # [linux]        
        - mkl                                    # [win]
        - mkl-devel                              # [win]
        - openblas                               # [not win]
        - ninja
        - numpy
        - pip
        - pkg-config
        - python
        - python-build
    run:
        - {{ pin_compatible('numpy') }}
        - python


test:
    imports:
        - pyhams
        - pyhams.pyhams
    requires:
        - pytest
    source_files:
        - test  # [ not win ]
    commands:
        - "cd test; pytest .; cd ..;"  # [ not win ]


about:
    home: https://github.com/WISDEM/pyHAMS
    license: Apache-2.0
    license_file: LICENSE
    summary: Python module wrapping around HAMS
    dev_url: https://github.com/WISDEM/pyHAMS
    
extra:
    recipe-maintainers:
        - mattEhall
        - dzalkind
        - gbarter
        - lucas-carmo
