{% set version = "1.2.2" %}

package:
  name: pyhams
  version: {{ version }}

source:
  url: https://github.com/WISDEM/pyHAMS/archive/v{{ version }}.tar.gz
  sha256: 43998f7f0e431b256e87890fd1c9cb31118e4da3c64d2d2962534a2840bf973e
  # Download the tar-ball and do: openssl sha256 file.tar.gz to update

build:
  number: 1
  skip: true  # [py<39]
  script:
    - del /s /q {{ BUILD_PREFIX }}\Library\mingw-w64\bin\pkg-config*  # [win]
    - {{ PYTHON }} -m build -n -x -w .
    - {{ PYTHON }} -m pip install --prefix {{ BUILD_PREFIX }} --no-deps --no-index -v --find-links dist pyhams
    #- {{ PYTHON }} -m pip install . --no-deps -vv
    - rm -rf {{ SP_DIR }}/meson_build       # [not win]
    - rmdir /s /q {{ SP_DIR }}\meson_build  # [win]
  #missing_dso_whitelist:
  #  - "*/libgfortran*.dll"    # [win]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('fortran') }}
    # use flang as fortran compiler on windows (uses clang driver)
    #- clang                                  # [win]
    #- flang                                  # [win]
    # use llvm linker for both of the above
    #- lld                                    # [win]
    # This brings in the whole m2w64-toolchain, including m2w64-pkgconfig that doesn't
    # find the right libraries compared to the regular conda version.  See above script
    # addition to "remove" the m2w64 pkg-config before installing
    - {{ compiler('m2w64_c') }}         # [win]
    #- {{ compiler('m2w64_fortran') }}   # [win]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    # Cmake is needed to help find libraries on windows
    - cmake       # [win]
    - meson
    - ninja
    - numpy
    - pip
    - pkg-config
    - python
    - python-build
    - wheel
    - llvm-openmp  # [osx]
    #- libgomp      # [linux or win]
    - openblas     # [win]
  host:
    - cython
    - libpython        # [win]
    - python
    - python-build
    - pip
    - numpy
    - setuptools
    - openblas
    #- libgomp      # [linux or win]
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libopenblas
    - m2w64-gcc-libgfortran  # [win]
    #- libgomp      # [linux or win]

test:
  imports:
    - pyhams
    - pyhams.pyhams
  #requires:
  #  - pip
  #commands:
  #  - cd test
  #  - pytest .

about:
  home: https://github.com/WISDEM/pyHAMS
  license: Apache-2.0
  license_file: LICENSE
  summary: Python module wrapping around HAMS
  dev_url: https://github.com/WISDEM/pyHAMS

extra:
  recipe-maintainers:
    - mattEhall
    - dzalkind
    - gbarter
    - lucas-carmo
