{% set version = "1.2.6" %}

package:
  name: pyhams
  version: {{ version }}

source:
  url: https://github.com/WISDEM/pyHAMS/archive/v{{ version }}.tar.gz
  sha256: 28d1b347a4f2ae287a87fdcec5ea69ff05d53e6cb1cfe32efdc4ca74dd21b6c7
  # Download the tar-ball and do: openssl sha256 file.tar.gz to update
  patches:
    - meson_files.patch

build:
  number: 1
  skip: true  # [py<39]
  #script:
  #  - echo "python = '${PREFIX}/bin/python'" >> ${BUILD_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
  #  - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - python                                  # [build_platform != target_platform]
    - meson-python                                  # [build_platform != target_platform]
    - meson                                  # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                                  # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libflang >=17.0                        # [win]
    # Cmake is needed to help find libraries on windows
    #- cmake         # [win]
    #- llvm-openmp   # [not linux]
    #- openblas      # [win]
  host:
    - python
    - pip
    - python-build
    - numpy
    - openblas
    - meson
    - meson-python
    - ninja
    - libgomp        # [linux]
    - libflang >=17.0     # [win]
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - ninja
    - libopenblas
    - llvm-openmp   # [not linux]
    - libflang >=17.0   # [win]

test:
  imports:
    - pyhams
    - pyhams.pyhams
  requires:
    - pytest
  source_files:
    - test  # [ not win ]
  commands:
    - "cd test; pytest .; cd ..;"  # [ not win ]


about:
  home: https://github.com/WISDEM/pyHAMS
  license: Apache-2.0
  license_file: LICENSE
  summary: Python module wrapping around HAMS
  dev_url: https://github.com/WISDEM/pyHAMS

extra:
  recipe-maintainers:
    - mattEhall
    - dzalkind
    - gbarter
    - lucas-carmo
