{% set version = "1.2.1" %}

package:
  name: pyhams
  version: {{ version }}

source:
  url: https://github.com/WISDEM/pyHAMS/archive/v{{ version }}.tar.gz
  sha256: 7d72a30cfb13be162c5aa2cea0e053ea82f5b0f638242f66452dc0dab454678e
  # Download the tar-ball and do: openssl sha256 file.tar.gz to update

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - rm -rf {{ SP_DIR }}/meson_build       # [not win]
    - rmdir /s /q {{ SP_DIR }}\meson_build  # [win]
    
requirements:
  build:
    - {{ compiler('fortran') }}
    # gcc is still needed in build process, although don't know why
    - {{ compiler('c') }}         # [not win]
    - {{ compiler('m2w64_c') }}   # [win]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    # Cmake is needed to help find libraries on windows
    - cmake       # [win]
    - meson
    - ninja
    - numpy
    - pip
    - pkg-config
    - python
    - python-build
    - wheel
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - cython
    - libpython        # [win]
    - python
    - python-build
    - pip
    - numpy
    - setuptools
    - openblas
    # Conda online help suggests putting these here only
    #- liblapack
    #- libblas
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libopenblas
    - m2w64-gcc-libgfortran  # [win]
    
test:
  imports:
    - pyhams
    - pyhams.pyhams
  #requires:
  #  - pip
  #commands:
  #  - cd test
  #  - pytest .

about:
  home: https://github.com/WISDEM/pyHAMS
  license: Apache-2.0
  license_file: LICENSE
  summary: Python module wrapping around HAMS
  dev_url: https://github.com/WISDEM/pyHAMS

extra:
  recipe-maintainers:
    - mattEhall
    - dzalkind
    - gbarter
    - lucas-carmo
