{% set version = "1.3.0" %}

package:
    name: pyhams
    version: {{ version }}

source:
    url: https://github.com/WISDEM/pyHAMS/archive/v{{ version }}.tar.gz
    sha256: d02bb27ed828f613232ba8e0d14e5d567a1081ede9fc6f963bf6163dda830c36
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
    patches:
        - meson_files.patch

build:
    number: 0
    skip: true  # [py<39]
    #script:
    #  - echo "python = '${PREFIX}/bin/python'" >> ${BUILD_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    #  - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
        - {{ stdlib("c") }}                      # [not win]
        - {{ compiler('c') }}                    # [not win]
        - {{ compiler('fortran') }}              # [not win]
        - {{ compiler('m2w64_c') }}              # [win]
        - {{ compiler('m2w64_fortran') }}        # [win]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - python                                 # [build_platform != target_platform]
        - meson                                  # [build_platform != target_platform]
        #- meson-python                           # [build_platform != target_platform]
        - ninja                                  # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - nomkl                                  # [build_platform != target_platform]
        - pkg-config                             # [build_platform != target_platform]
        - wheel                                  # [build_platform != target_platform]
        - python-build                           # [build_platform != target_platform]
    host:
        #- compiler-rt                            # [win]
        - libpython                              # [win]
        - cython
        - llvm-openmp                            # [osx or win]
        - libgomp                                # [linux]        
        - meson
        #- meson-python
        - numpy
        - nomkl                                  # [win]
        - pkg-config
        - python
        - python-build
        - pip
        - setuptools
    run:
        - {{ pin_compatible('numpy') }}
        - python
        - nomkl                                  # [win]

test:
    imports:
        - pyhams
        - pyhams.pyhams
    requires:
        - pytest
    source_files:
        - test
        - test/Cylinder
        - test/Cylinder/Input
        - test/Cylinder/truth
        - test/Cylinder_headings
        - test/Cylinder_headings/Input
        - test/Cylinder_headings/truth
    commands:
        - cd test
        - pytest .
        - cd ..


about:
    home: https://github.com/WISDEM/pyHAMS
    license: Apache-2.0
    license_file: LICENSE
    summary: Python module wrapping around HAMS
    dev_url: https://github.com/WISDEM/pyHAMS
    
extra:
    recipe-maintainers:
        - mattEhall
        - dzalkind
        - gbarter
        - lucas-carmo
