schema_version: 1

context:
    version: "1.3.1"
    name: pyhams
    build_number: 3

package:
    name: ${{ name }}
    version: ${{ version }}

source:
    url: https://github.com/NLRWindSystems/pyHAMS/archive/v${{ version }}.tar.gz
    sha256: 84c4d51df3383c596cd66646a6283cfb75f0afa283f434e5a7ae418f0efbb251

build:
    number: ${{ build_number }}
    skip:
        - match(python, "<3.10")

requirements:
    build:
        - if: not win
          then:
              - ${{ stdlib("c") }}
              - ${{ compiler('c') }}
              - ${{ compiler('fortran') }}
        - if: win
          then:
              - ${{ compiler('m2w64_c') }}
              - ${{ compiler('m2w64_fortran') }}
        - if: build_platform != target_platform
          then:
              - cross-python_${{ target_platform }}
              - python
              - meson
              - ninja
              - numpy
              - nomkl
              - pkg-config
              - wheel
              - python-build
    host:
        - if: win
          then:
              - libpython
              - nomkl
        - if: win or osx
          then:
              - llvm-openmp
        - if: linux
          then:
              - libgomp
        - cython
        - meson
        - numpy
        - pkg-config
        - python
        - python-build
        - pip
        - setuptools
    run:
        - if: win
          then:
              - nomkl
        - python

tests:
    - python:
          imports:
              - pyhams
              - pyhams.pyhams
                
    - script:
          - cd test && pytest . && cd ..
      requirements:
          run:
              - pytest
      files:
          source:
              - test
              - test/Cylinder
              - test/Cylinder/Input
              - test/Cylinder/truth
              - test/Cylinder_headings
              - test/Cylinder_headings/Input
              - test/Cylinder_headings/truth
      pip_check: false

about:
    homepage: https://github.com/NLRWindSystems/pyHAMS
    license: Apache-2.0
    license_file: LICENSE
    summary: Python module wrapping around HAMS
    description: |
        pyHAMS is a python wrapper for HAMS, a boundary element method for hydrodynamic
        analysis of submerged structures.
    repository: https://github.com/NLRWindSystems/pyHAMS
    documentation: https://github.com/NLRWindSystems/pyHAMS

extra:
    recipe-maintainers:
        - mattEhall
        - dzalkind
        - gbarter
        - lucas-carmo
